name: sksurv-test
channels:
  - sebp
  - defaults
dependencies:
  - coverage
  - cython>=0.29
  - ecos
  - ipykernel
  - ipython!=8.7.0
  - joblib
  - matplotlib>=3.6.2,<3.7
  - nbformat
  - numexpr
  - numpy=*
  - osqp!=0.6.0,!=0.6.1
  - packaging
  - pandas=*
  - pip
  - pytest
  - python=*
  - scikit-learn=*
  - scipy>=1.3.2
  - seaborn>=0.11.2,<0.12
  - setuptools-scm
  - wheel
  - pip:
    - black[jupyter]>=23.3.0,<23.4
    - build
    - importlib-resources>=1.3
    - nbval>=0.10.0
    - tomli
